//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.QueryResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UsageQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UsageQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataAccess.QueryResources.UsageQueries", typeof(UsageQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT UsageGuid 
        /// ,u.CustomerGuid 
        /// ,u.Rate 
        /// ,lrc.RateDescription 
        /// ,cl.QualifiedRate
        /// ,u.IsActive 
        /// ,u.AverageUsage 
        /// ,u.UsageDays 
        /// ,u.HeatingAverageUsage 
        /// ,u.HeatingUsageDays 
        /// ,case when u.Rate = cl.QualifiedRate then 1 else 0 END as &apos;IsQual&apos;
        /// FROM Customer.Usage u 
        /// INNER JOIN customer.Lead cl on cl.CustomerGuid = u.CustomerGuid
        /// INNER JOIN UsageRaw.LkpRateCodes lrc on lrc.RateCode = u.Rate 
        /// WHERE u.CustomerGuid =   @CustomerGuid 
        /// and not (u.AverageUsage is null and UsageDays is nul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetUsageByCustomerGuid {
            get {
                return ResourceManager.GetString("GetUsageByCustomerGuid", resourceCulture);
            }
        }
    }
}
